version: '2'
services:
    site_web:
        image: 'bitnami/apache:latest'
        container_name: 'site_web'
        user: root
        ports:
            - 80:8080
        volumes: 
            - type: volume
              source: data_logs
              target: /opt/bitnami/apache2/logs 
            - type: bind 
              source: ./stack/httpd.conf
              target: /opt/bitnami/apache2/conf/httpd.conf
    fb_collect_logs:
        image: 'docker.elastic.co/beats/filebeat:7.6.2'
        container_name: 'fb_collect_logs'
        user: root
        volumes: 
            - type: volume
              source: data_logs
              target: /usr/share/filebeat/data  
            - type: bind
              source: ./stack/filebeat.yml
              target: /usr/share/filebeat/filebeat.yml
        command: filebeat -e -strict.perms=false
        depends_on: 
            - site_web   
        networks:
            - elk_network

    zookeeper: 
        image: 'bitnami/zookeeper:latest'
        restart: always
        hostname: zookeeper
        ports: 
            - 2181:2181
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        networks: 
            - elk_network 
        depends_on: 
            - fb_collect_logs
    
    kafka:
        image: 'bitnami/kafka:latest'
        hostname: kafka
        ports:
            - 9092:9092
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
        networks:
            - elk_network
    
    logstash:
        container_name: logstash
        image: 'docker.elastic.co/logstash/logstash:7.6.2'
        ports:
            - 5044:5044
        volumes:
            - type: bind
              source: ./stack/pipeline_web_logs.conf
              target: /usr/share/logstash/pipeline/logstash.conf
        environment:
            LS_JAVA_OPTS: "-Xms256m -Xms256m"
        networks:
            - elk_network
        depends_on:
            - elasticsearch
            - kafka
    
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        container_name: elasticsearch
        environment: 
            - cluster.name=cluster
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - cluster.routing.allocation.disk.threshold_enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - type: volume
              source: esdata1
              target: /usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - elk_network
    
    kibana:
        image: docker.elastic.co/kibana/kibana:7.6.2
        container_name: kibana
        environment:
            SERVER_NAME: kibana
            ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
        ports:
            - 5601:5601
        networks: 
            - elk_network
        depends_on:
            - elasticsearch 

volumes:
    data_logs:
        driver: local
    esdata1: 
        driver: local

networks:
    elk_network:
        driver: bridge
